version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: catalyst
      POSTGRES_USER: media
      POSTGRES_PASSWORD: catalyst123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
